const products=[
 {id:1,name:'Свеча «Тёплый вечер»',price:990,category:'candles',tag:'ХИТ',image:'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=700&q=80'},
 {id:2,name:'Кружка «Облако»',price:790,category:'table',tag:'НОВОЕ',image:'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=700&q=80'},
 {id:3,name:'Ваза «Тихий сад»',price:1490,category:'decor',tag:'',image:'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=700&q=80'},
 {id:4,name:'Свеча «Утро в саду»',price:1090,category:'candles',tag:'',image:'https://images.unsplash.com/photo-1602523961358-f9f03dd557db?auto=format&fit=crop&w=700&q=80'},
 {id:5,name:'Тарелка «Молоко»',price:690,category:'table',tag:'',image:'https://images.unsplash.com/photo-1603199506016-b9a594b593c0?auto=format&fit=crop&w=700&q=80'},
 {id:6,name:'Льняная салфетка',price:490,category:'decor',tag:'',image:'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=700&q=80'}
];
let cart=JSON.parse(localStorage.getItem('luna-cart')||'[]');
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' сом';
function save(){localStorage.setItem('luna-cart',JSON.stringify(cart));renderCount();}
function renderCount(){const n=cart.reduce((s,i)=>s+i.qty,0);document.querySelectorAll('[data-cart-count]').forEach(x=>x.textContent=n)}
function card(p){return `<article class="product-card" data-category="${p.category}" data-price="${p.price}"><div class="product-image"><img src="${p.image}" alt="${p.name}">${p.tag?`<span>${p.tag}</span>`:''}</div><h3>${p.name}</h3><p>${money(p.price)}</p><button class="add" data-add="${p.id}">В корзину +</button></article>`}
function showToast(message){const toast=document.querySelector('.toast');if(!toast)return;toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2100)}
function add(id){const found=cart.find(x=>x.id===id);if(found)found.qty++;else cart.push({id,qty:1});save();showToast('Добавлено в корзину ✦');}
function paintProducts(){const catalog=document.querySelector('.catalog');const featured=document.querySelector('.featured-products');if(catalog)catalog.innerHTML=products.map(card).join('');if(featured)featured.innerHTML=products.slice(0,3).map(card).join('');}
function renderCart(){const root=document.querySelector('.cart-items');if(!root)return;const total=cart.reduce((sum,item)=>sum+products.find(p=>p.id===item.id).price*item.qty,0);root.innerHTML=cart.length?cart.map(item=>{const p=products.find(x=>x.id===item.id);return `<article class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>${money(p.price)}</p><div class="qty"><button data-qty="${p.id}" data-change="-1">−</button><span>${item.qty}</span><button data-qty="${p.id}" data-change="1">+</button></div></div><strong>${money(p.price*item.qty)}</strong><button class="remove" data-remove="${p.id}">Удалить</button></article>`}).join(''):'<div class="empty">Здесь пока пусто. <a href="catalog.html">Выбрать что-нибудь красивое →</a></div>';
 document.querySelectorAll('[data-total]').forEach(x=>x.textContent=money(total));const delivery=document.querySelector('[data-delivery]');if(delivery)delivery.textContent=total===0?'—':total>=3000?'Бесплатно':'250 сом';}
paintProducts();renderCount();renderCart();
document.addEventListener('click',e=>{const addButton=e.target.closest('[data-add]');if(addButton)add(+addButton.dataset.add);const q=e.target.closest('[data-qty]');if(q){const item=cart.find(x=>x.id===+q.dataset.qty);item.qty+=+q.dataset.change;if(item.qty<1)cart=cart.filter(x=>x!==item);save();renderCart()}const remove=e.target.closest('[data-remove]');if(remove){cart=cart.filter(x=>x.id!==+remove.dataset.remove);save();renderCart()}});
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelectorAll('.catalog .product-card').forEach(card=>card.hidden=button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter)}));
const requested=new URLSearchParams(location.search).get('category');if(requested){const button=document.querySelector(`[data-filter="${requested}"]`);button?.click()}
document.querySelector('.sort select')?.addEventListener('change',e=>{const grid=document.querySelector('.catalog');const items=[...grid.children];items.sort((a,b)=>e.target.value==='low'?+a.dataset.price-+b.dataset.price:e.target.value==='high'?+b.dataset.price-+a.dataset.price:0);items.forEach(item=>grid.append(item))});
document.querySelector('.menu')?.addEventListener('click',()=>document.querySelector('nav').classList.toggle('open'));
document.querySelectorAll('.subscribe').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();form.reset();showToast('Ты в списке — до встречи в письмах!') }));
const modal=document.querySelector('.order-modal');document.querySelector('.checkout')?.addEventListener('click',()=>{if(!cart.length)return showToast('Сначала добавь что-нибудь в корзину');modal.showModal()});document.querySelector('.close-modal')?.addEventListener('click',()=>modal.close());document.querySelector('.order-form')?.addEventListener('submit',e=>{e.preventDefault();cart=[];save();renderCart();modal.close();showToast('Спасибо! Заказ принят ✦')});
